/** Major ID descriptions sourced from the Wynncraft Wiki. */
export const MAJOR_ID_DESCRIPTIONS: Record<string, string> = {
  'Alter Ego': 'Awakened can be activated after saving 40% less mana, but its duration is reduced by 25%.',
  'Altruism': 'Nearby players gain 100% of the health you gain from Health Regen and Life Steal while you are not at full health.',
  'Brachiate': 'Grappling Hook has 25% increased range and increased velocity, but no longer pulls enemies.',
  'Cannulate': 'Sacrificial Shrine costs -5 Blood Pool to cast, but health drain is reduced by half.',
  'Cavalryman': 'You may cast spells and attack with a -30% damage penalty while on a horse.',
  'Cherry Bombs': 'Turns Smoke Bomb into firecrackers that fly farther, tighter, and deal 100%, 30%, 30%, and 30% instantly.',
  'Coagulate': "Blood Connection and Eldritch Call's teleports launch you further and higher.",
  'Combo Stomp': 'Landing directly on an enemy with Fierce Stomp sends you back into the air and resets Escape.',
  'Dauntless Inferno': 'Courage casts a series of 5 infernos that expand after the last, dealing 125% damage each, and grants 20% resistance instead of a damage boost.',
  'Dead Weight': "Totem's horizontal velocity is greatly increased at the cost of vertical movement.",
  'Displace': 'Wind Slash deals massive knockback to enemies hit by Teleport.',
  'Divine Honor': "Increases the bonus from Radiance by 10%. Bash deals -15% per hit.",
  'Earthen Splinter': 'Quake channels nature energy into a powerful root, travelling underground and emerging under the nearest mob for 1200%.',
  'Efflorescence': "Jasmine Bloom deals 25% and 25% at the cost of 6 blocks of vertical range. Swan Dive deals 16% and 16%.",
  'Entropy': "Meteor's speed is increased by 50%.",
  'Ergosphere': 'Storm Dance instead lets your Totems pull enemies within their radius. Totem duration is decreased.',
  'Escape Route': 'Frenzy and Time Dilation charge twice as fast but also decay twice as fast.',
  'Evershot': 'Arrow Hurricane becomes a consistent, straight stream of arrows with a slower fire rate, dealing greater knockback and triple damage per arrow.',
  'Explosive Impact': 'Enemies explode on death, dealing 300% Main Attack damage in a radius of 5 blocks.',
  'Expunge': 'When using Heal, cast one instant pulse that heals 15% of your max health.',
  'Fallout': 'Bomb Arrow gains +7.5 range, +50%, severely increased recoil, and 25% self-damage.',
  'Fan the Hammer': 'Arrow Storm becomes a single stream of 6 high-powered arrows that deal 90% and 35%.',
  'Faustian Gambit': 'Frog Dance triggers once with increased vertical velocity and knockback, and deals +400%.',
  'Festive Spirit': 'Plays the Wynncraft OST track "Craftmas Carol" while worn.',
  'Find Thyself': 'Masquerade now grants 75 Mana after switching between Masks 3 times.',
  'Fission': 'Explosions from your Exploding ID are twice as big and twice as strong.',
  'Fixate': "Devitalize doubles your Winded cap, but lowers Winded damage effects by 30%. Timelock absorbs up to 120 Winded.",
  'Flashfreeze': 'Ice Snake travels instantly.',
  'Flurry of Blows': 'Turn Double Slice into a 10-hit pummeling of 16% damage per hit.',
  "Forest's Blessing": "Your archer summons have increased movement speed, attack speed, vision, and +60%. Bomb Arrow's damage is reduced by -30%.",
  'Freerunner': 'When your sprint bar is under 30% full, increase your sprint speed by +150%.',
  'Frenetic Spirit': "Guardian Angels damage is set to 10%, but shoot 40% faster and last 5 times longer. Frenzy's cap is increased by 55.",
  'Fright or Flight': 'Plays the Wynncraft OST track "Bumps in the Night" while worn.',
  'Furious Effigy': 'Totem effects are twice as fast, but duration is halved.',
  'Gentle Glow': "Orphion's Pulse restores 20% more health to allies, but heals at a slower rate. Fluid Healing's effectiveness is increased by 150%.",
  'Geocentrism': 'Aura radiates from you instead of your Totem and can be cast any time.',
  'Gravity Well': "Meteor's radius is increased by 3 blocks, and it pulls enemies instead of dealing knockback.",
  'Greed': 'Picking up emeralds heals you and nearby players for 8% max health.',
  'Gruesome Knots': 'Bleeding and Twisted Tether deal double damage, but Bleeding duration is reduced.',
  'Guardian': '35% of damage taken by nearby allies is redirected to you.',
  'Hawkeye': 'Arrow Hurricane becomes a condensed stream of 25 arrows, dealing 25%, 5%, and 5% each.',
  'Heartbeat': 'Arrow Shield is locked to 2 charges but deals doubled damage. Arrow Wall triples Arrow Shield damage and doubles Guardian Angels ammo.',
  'Heat Shimmer': 'Foul Play will no longer slay a Mirror Clone and will still provide its effects, but Mirror Clone count is reduced to 1. Tricks application is increased by 50%.',
  'Hellfire': "Bash is replaced by a single hit, gaining +3 radius and dealing +85%, +10%, and +60%. Boiling Blood's cooldown is set to 2s, gains +40%, +50%, and burns twice as fast for 1s, but can't slow.",
  "Hurricane's Eye": 'Violent Vortex applies 2 marks to every enemy it hits.',
  'Insoluble': 'Dissolution now lasts 2.5 seconds, but grants only 35% resistance.',
  'Intangible': 'The knockback you take is drastically reduced, and reflected damage deals large knockback.',
  'Inversion': 'Teleport will grant you 3 seconds of levitation.',
  'Juggle': 'Stronger Multihit adds an additional 12 hits. All hits are reduced by -10%.',
  'Last Resort': 'Bloodlust has doubled corrupted scaling and knockback, but deals -100% -60%.',
  'Lifestream': 'Blood Sorrow deals 450% and grants 4 times the overhealth, but shortens its duration by 75%.',
  'Lightweight': 'You no longer take fall damage.',
  'Lockdown': 'Meteor will snap onto a target in range, regardless of aim.',
  'Lunge': "Hop and Leap's horizontal velocity is greatly increased.",
  'Lustrate': 'Heal restores health at a slower rate, but Searing Light deals +150%.',
  'Madness': 'Casts a random spell of your class every 3 seconds.',
  'Magnet': 'Pulls items within an 8 block radius towards you.',
  'Mangle': 'Lacerate will deal +1 slash.',
  'Meteor Crash': 'Burning Sigil gains +6 radius and deals double the damage, but lasts half as long.',
  'Methodical': "Initiator's reset time is reduced by 75%. Arrow Bomb area damage is halved, but direct hit damage is doubled.",
  'Napalm': "Fire Creep increases Arrow Bomb damage by +15%, but deals 15 times the self-damage and lowers velocity. Scorched Earth radius is increased and deals +65%.",
  'Orbital Chain': 'Chain Lightning hits slower, rebounds, adds 6 chains, and pulls mobs closer for a 1500% explosion spell.',
  'Overwhelm': 'Bash will hit +2 times.',
  'Paragon': "Shield Strike deals 600%. Mantle of the Bovemist's cooldown is reduced by 15s, but is limited to one shield charge.",
  'Peaceful Effigy': 'Your totem will last twice as long.',
  'Perfect Recall': "Memory Recollection speeds up Chaos Explosion by 0.1s per spell but increases Chaos Explosion's mana bank requirement by 30.",
  'Perilous Flare': 'Pyrokinesis moves much slower, but has an increased Area of Effect and +50%.',
  'Phoenix-Born': 'Health Regeneration is increased by 0.75% for every 1% Health missing.',
  "Pioneer's Echo": "Phantom Ray deals two bursts of 150%, 60% over 1.1 seconds. Decimator's increase and cap are raised to 100%.",
  'Plague': 'Poisoned mobs spread their poison to nearby mobs.',
  'Pounce': 'Escape becomes a forward lunge.',
  'Power Fist': 'Striking enemies with an empty hand greatly knocks them back.',
  'Punishment': 'Reflected damage blinds enemies for 1s and makes them 10% more vulnerable to attacks for 3s.',
  'Rally': 'Cleansing Breeze causes Charge to heal you for 15% and nearby allies for 20%, but Charge becomes harmless.',
  'Reality Revision': "Phasing Beam instead makes Twain's Arc explode upon hitting an enemy, dealing its damage in a 5 block radius. Twain's Arc now has extreme recoil.",
  'Reckless Abandon': 'Sacrifice War Scream\'s defense bonus to give Tempest +5% +15% +5% and 3 extra hits.',
  'Rock Shield': "Arrow Shield's defense is increased by 10%, but its number of charges is reduced by 1.",
  'Roving Assassin': 'Vanish will no longer block mana and health regeneration.',
  'Rusted Ichor': 'Boiling Blood cooldown is reduced by 0.5s and inflicts 40% slowness, but deals no damage.',
  "Saviour's Sacrifice": 'While under 50% maximum health, nearby allies gain 15% bonus damage and defense.',
  'Scarce Comfort': 'Freestream Flow becomes slightly stronger and lasts indefinitely.',
  'Seeking Module': 'Homing Shots track towards nearby enemies much more aggressively.',
  'Self-sufficient': 'Powder Specials can no longer be charged manually, but accumulate 8% charge every second.',
  'Snowy Steps': 'Leaves a trail of snow behind you.',
  'Sorcery': '25% chance for spells and attacks to cast a second time at no additional cost.',
  'Soul Eater': 'Devour and Harvester grant double mana. Decreases maximum marks by 1.',
  'Space Glide': 'Lacerate performs a single horizontal jump and slash, dealing 400%.',
  'Spectral Memory': 'Ghostly Trigger lasts until landing, but no longer increases attack speed. Its cooldown is reduced by 33%.',
  'Strings of Fate': 'Your puppets have a lifetime of 3 seconds and deal double damage with attacks and explosions.',
  'Sublimation': "Totemic Shatter heals 75% of Regeneration's usual amount at the cost of 2 blocks of radius.",
  'Sun Eater': 'Failing to backstab an enemy from behind blinds them for 0.5s and slows them by 20% for 5s.',
  'Superconductor': 'Chain Lightning channels three massive lightning bolts through you, arcing to enemies within 8 blocks for 225% and stunning them for 1s. You take 10% more damage for 4s.',
  'Tackle': 'Flying Kick deals much more knockback and increases Collide damage by an additional +150% +60% +10%.',
  'Taunt': "Provoke's cooldown is lowered by -3s.",
  'Temblor': 'Bash gains +1 Area of Effect and is 0.05s faster.',
  'Tidal Drift': 'Flying Kick will instead send you forwards. This effect is limited to once per Charge cast.',
  'Totemic Fuse': "Totemic Smash deals +40% +90% +90% +60% at the cost of half of Totem's duration.",
  'Transcendence': '25% chance for spells to cost no mana when casted.',
  'Windsurf': "Arrow Shield now boosts your movement speed instead of blocking damage. Escape and Leap's vertical velocity are increased.",
};

export function getMajorIdDescription(name: string): string | null {
  return MAJOR_ID_DESCRIPTIONS[name] ?? null;
}
