/** Major ID info keyed by API identifier (UPPER_SNAKE_CASE). */
const MAJOR_ID_INFO: Record<string, { name: string; desc: string }> = {
  ALTEREGO: { name: 'Alter Ego', desc: 'Awakened can be activated after saving 40% less mana, but its duration is reduced by 25%.' },
  ALTRUISM: { name: 'Altruism', desc: 'Nearby players gain 100% of the health you gain from Health Regen and Life Steal while you are not at full health.' },
  BRACHIATE: { name: 'Brachiate', desc: 'Grappling Hook has 25% increased range and increased velocity, but no longer pulls enemies.' },
  CANNULATE: { name: 'Cannulate', desc: 'Sacrificial Shrine costs -5 Blood Pool to cast, but health drain is reduced by half.' },
  CAVALRYMAN: { name: 'Cavalryman', desc: 'You may cast spells and attack with a -30% damage penalty while on a horse.' },
  CHERRY_BOMBS: { name: 'Cherry Bombs', desc: 'Turns Smoke Bomb into firecrackers that fly farther, tighter, and deal 100%, 30%, 30%, and 30% instantly.' },
  COAGULATE: { name: 'Coagulate', desc: "Blood Connection and Eldritch Call's teleports launch you further and higher." },
  COMBO_STOMP: { name: 'Combo Stomp', desc: 'Landing directly on an enemy with Fierce Stomp sends you back into the air and resets Escape.' },
  DAUNTLESS_INFERNO: { name: 'Dauntless Inferno', desc: 'Courage casts a series of 5 infernos that expand after the last, dealing 125% damage each, and grants 20% resistance instead of a damage boost.' },
  DEADWEIGHT: { name: 'Dead Weight', desc: "Totem's horizontal velocity is greatly increased at the cost of vertical movement." },
  DISPLACE: { name: 'Displace', desc: 'Wind Slash deals massive knockback to enemies hit by Teleport.' },
  DIVINE_HONOR: { name: 'Divine Honor', desc: "Increases the bonus from Radiance by 10%. Bash deals -15% per hit." },
  EARTHEN_SPLINTER: { name: 'Earthen Splinter', desc: 'Quake channels nature energy into a powerful root, travelling underground and emerging under the nearest mob for 1200%.' },
  EFFLORESCENCE: { name: 'Efflorescence', desc: "Jasmine Bloom deals 25% and 25% at the cost of 6 blocks of vertical range. Swan Dive deals 16% and 16%." },
  ENTROPY: { name: 'Entropy', desc: "Meteor's speed is increased by 50%." },
  ERGOSPHERE: { name: 'Ergosphere', desc: 'Storm Dance instead lets your Totems pull enemies within their radius. Totem duration is decreased.' },
  ESCAPE_ROUTE: { name: 'Escape Route', desc: 'Frenzy and Time Dilation charge twice as fast but also decay twice as fast.' },
  EVERSHOT: { name: 'Evershot', desc: 'Arrow Hurricane becomes a consistent, straight stream of arrows with a slower fire rate, dealing greater knockback and triple damage per arrow.' },
  EXPLOSIVE_IMPACT: { name: 'Explosive Impact', desc: 'Enemies explode on death, dealing 300% Main Attack damage in a radius of 5 blocks.' },
  EXPUNGE: { name: 'Expunge', desc: 'When using Heal, cast one instant pulse that heals 15% of your max health.' },
  FALLOUT: { name: 'Fallout', desc: 'Bomb Arrow gains +7.5 range, +50%, severely increased recoil, and 25% self-damage.' },
  FAN_THE_HAMMER: { name: 'Fan the Hammer', desc: 'Arrow Storm becomes a single stream of 6 high-powered arrows that deal 90% and 35%.' },
  FAUSTIAN_GAMBIT: { name: 'Faustian Gambit', desc: 'Frog Dance triggers once with increased vertical velocity and knockback, and deals +400%.' },
  DESC_FESTIVESPIRIT: { name: 'Festive Spirit', desc: 'Plays the Wynncraft OST track "Craftmas Carol" while worn.' },
  FIND_THYSELF: { name: 'Find Thyself', desc: 'Masquerade now grants 75 Mana after switching between Masks 3 times.' },
  FISSION: { name: 'Fission', desc: 'Explosions from your Exploding ID are twice as big and twice as strong.' },
  FIXATE: { name: 'Fixate', desc: "Devitalize doubles your Winded cap, but lowers Winded damage effects by 30%. Timelock absorbs up to 120 Winded." },
  FLASHFREEZE: { name: 'Flashfreeze', desc: 'Ice Snake travels instantly.' },
  FLURRY_OF_BLOWS: { name: 'Flurry of Blows', desc: 'Turn Double Slice into a 10-hit pummeling of 16% damage per hit.' },
  FOREST_BLESSING: { name: "Forest's Blessing", desc: "Your archer summons have increased movement speed, attack speed, vision, and +60%. Bomb Arrow's damage is reduced by -30%." },
  FREERUNNER: { name: 'Freerunner', desc: 'When your sprint bar is under 30% full, increase your sprint speed by +150%.' },
  FRENETIC_SPIRIT: { name: 'Frenetic Spirit', desc: "Guardian Angels damage is set to 10%, but shoot 40% faster and last 5 times longer. Frenzy's cap is increased by 55." },
  FRIGHT_OR_FLIGHT: { name: 'Fright or Flight', desc: 'Plays the Wynncraft OST track "Bumps in the Night" while worn.' },
  FURIOUS_EFFIGY: { name: 'Furious Effigy', desc: 'Totem effects are twice as fast, but duration is halved.' },
  GENTLE_GLOW: { name: 'Gentle Glow', desc: "Orphion's Pulse restores 20% more health to allies, but heals at a slower rate. Fluid Healing's effectiveness is increased by 150%." },
  GEOCENTRISM: { name: 'Geocentrism', desc: 'Aura radiates from you instead of your Totem and can be cast any time.' },
  GRAVITYWELL: { name: 'Gravity Well', desc: "Meteor's radius is increased by 3 blocks, and it pulls enemies instead of dealing knockback." },
  GREED: { name: 'Greed', desc: 'Picking up emeralds heals you and nearby players for 8% max health.' },
  GRUESOME_KNOTS: { name: 'Gruesome Knots', desc: 'Bleeding and Twisted Tether deal double damage, but Bleeding duration is reduced.' },
  GUARDIAN: { name: 'Guardian', desc: '35% of damage taken by nearby allies is redirected to you.' },
  HAWKEYE: { name: 'Hawkeye', desc: 'Arrow Hurricane becomes a condensed stream of 25 arrows, dealing 25%, 5%, and 5% each.' },
  HEARTBEAT: { name: 'Heartbeat', desc: 'Arrow Shield is locked to 2 charges but deals doubled damage. Arrow Wall triples Arrow Shield damage and doubles Guardian Angels ammo.' },
  HEAT_SHIMMER: { name: 'Heat Shimmer', desc: 'Foul Play will no longer slay a Mirror Clone and will still provide its effects, but Mirror Clone count is reduced to 1. Tricks application is increased by 50%.' },
  HELLFIRE: { name: 'Hellfire', desc: "Bash is replaced by a single hit, gaining +3 radius and dealing +85%, +10%, and +60%. Boiling Blood's cooldown is set to 2s, gains +40%, +50%, and burns twice as fast for 1s, but can't slow." },
  HURRICANES_EYE: { name: "Hurricane's Eye", desc: 'Violent Vortex applies 2 marks to every enemy it hits.' },
  INSOLUBLE: { name: 'Insoluble', desc: 'Dissolution now lasts 2.5 seconds, but grants only 35% resistance.' },
  INTANGIBLE: { name: 'Intangible', desc: 'The knockback you take is drastically reduced, and reflected damage deals large knockback.' },
  INVERSION: { name: 'Inversion', desc: 'Teleport will grant you 3 seconds of levitation.' },
  JUGGLE: { name: 'Juggle', desc: 'Stronger Multihit adds an additional 12 hits. All hits are reduced by -10%.' },
  LAST_RESORT: { name: 'Last Resort', desc: 'Bloodlust has doubled corrupted scaling and knockback, but deals -100% -60%.' },
  LIFESTREAM: { name: 'Lifestream', desc: 'Blood Sorrow deals 450% and grants 4 times the overhealth, but shortens its duration by 75%.' },
  LIGHTWEIGHT: { name: 'Lightweight', desc: 'You no longer take fall damage.' },
  LOCKDOWN: { name: 'Lockdown', desc: 'Meteor will snap onto a target in range, regardless of aim.' },
  LUNGE: { name: 'Lunge', desc: "Hop and Leap's horizontal velocity is greatly increased." },
  LUSTRATE: { name: 'Lustrate', desc: 'Heal restores health at a slower rate, but Searing Light deals +150%.' },
  MADNESS: { name: 'Madness', desc: 'Casts a random spell of your class every 3 seconds.' },
  MAGNET: { name: 'Magnet', desc: 'Pulls items within an 8 block radius towards you.' },
  MANGLE: { name: 'Mangle', desc: 'Lacerate will deal +1 slash.' },
  METEOR_CRASH: { name: 'Meteor Crash', desc: 'Burning Sigil gains +6 radius and deals double the damage, but lasts half as long.' },
  METHODICAL: { name: 'Methodical', desc: "Initiator's reset time is reduced by 75%. Arrow Bomb area damage is halved, but direct hit damage is doubled." },
  NAPALM: { name: 'Napalm', desc: "Fire Creep increases Arrow Bomb damage by +15%, but deals 15 times the self-damage and lowers velocity. Scorched Earth radius is increased and deals +65%." },
  ORBITAL_CHAIN: { name: 'Orbital Chain', desc: 'Chain Lightning hits slower, rebounds, adds 6 chains, and pulls mobs closer for a 1500% explosion spell.' },
  OVERWHELM: { name: 'Overwhelm', desc: 'Bash will hit +2 times.' },
  PARAGON: { name: 'Paragon', desc: "Shield Strike deals 600%. Mantle of the Bovemist's cooldown is reduced by 15s, but is limited to one shield charge." },
  PEACEFUL_EFFIGY: { name: 'Peaceful Effigy', desc: 'Your totem will last twice as long.' },
  PERFECT_RECALL: { name: 'Perfect Recall', desc: "Memory Recollection speeds up Chaos Explosion by 0.1s per spell but increases Chaos Explosion's mana bank requirement by 30." },
  PERILOUS_FLARE: { name: 'Perilous Flare', desc: 'Pyrokinesis moves much slower, but has an increased Area of Effect and +50%.' },
  PHOENIXBORN: { name: 'Phoenix-Born', desc: 'Health Regeneration is increased by 0.75% for every 1% Health missing.' },
  PIONEERS_ECHO: { name: "Pioneer's Echo", desc: "Phantom Ray deals two bursts of 150%, 60% over 1.1 seconds. Decimator's increase and cap are raised to 100%." },
  PLAGUE: { name: 'Plague', desc: 'Poisoned mobs spread their poison to nearby mobs.' },
  POUNCE: { name: 'Pounce', desc: 'Escape becomes a forward lunge.' },
  POWER_FIST: { name: 'Power Fist', desc: 'Striking enemies with an empty hand greatly knocks them back.' },
  PUNISHMENT: { name: 'Punishment', desc: 'Reflected damage blinds enemies for 1s and makes them 10% more vulnerable to attacks for 3s.' },
  RALLY: { name: 'Rally', desc: 'Cleansing Breeze causes Charge to heal you for 15% and nearby allies for 20%, but Charge becomes harmless.' },
  REALITY_REVISION: { name: 'Reality Revision', desc: "Phasing Beam instead makes Twain's Arc explode upon hitting an enemy, dealing its damage in a 5 block radius. Twain's Arc now has extreme recoil." },
  RECKLESS_ABANDON: { name: 'Reckless Abandon', desc: "Sacrifice War Scream's defense bonus to give Tempest +5% +15% +5% and 3 extra hits." },
  ROCK_SHIELD: { name: 'Rock Shield', desc: "Arrow Shield's defense is increased by 10%, but its number of charges is reduced by 1." },
  ROVINGASSASSIN: { name: 'Roving Assassin', desc: 'Vanish will no longer block mana and health regeneration.' },
  RUSTED_ICHOR: { name: 'Rusted Ichor', desc: 'Boiling Blood cooldown is reduced by 0.5s and inflicts 40% slowness, but deals no damage.' },
  SCARCE_COMFORT: { name: 'Scarce Comfort', desc: 'Freestream Flow becomes slightly stronger and lasts indefinitely.' },
  SEEKING_MODULE: { name: 'Seeking Module', desc: 'Homing Shots track towards nearby enemies much more aggressively.' },
  SELFSUFFICIENT: { name: 'Self-sufficient', desc: 'Powder Specials can no longer be charged manually, but accumulate 8% charge every second.' },
  DESC_SNOWYSTEPS: { name: 'Snowy Steps', desc: 'Leaves a trail of snow behind you.' },
  SORCERY: { name: 'Sorcery', desc: '25% chance for spells and attacks to cast a second time at no additional cost.' },
  SOUL_EATER: { name: 'Soul Eater', desc: 'Devour and Harvester grant double mana. Decreases maximum marks by 1.' },
  SPACE_GLIDE: { name: 'Space Glide', desc: 'Lacerate performs a single horizontal jump and slash, dealing 400%.' },
  SPECTRAL_MEMORY: { name: 'Spectral Memory', desc: 'Ghostly Trigger lasts until landing, but no longer increases attack speed. Its cooldown is reduced by 33%.' },
  STRINGS_OF_FATE: { name: 'Strings of Fate', desc: 'Your puppets have a lifetime of 3 seconds and deal double damage with attacks and explosions.' },
  SUBLIMATION: { name: 'Sublimation', desc: "Totemic Shatter heals 75% of Regeneration's usual amount at the cost of 2 blocks of radius." },
  SUN_EATER: { name: 'Sun Eater', desc: 'Failing to backstab an enemy from behind blinds them for 0.5s and slows them by 20% for 5s.' },
  SUPERCONDUCTOR: { name: 'Superconductor', desc: 'Chain Lightning channels three massive lightning bolts through you, arcing to enemies within 8 blocks for 225% and stunning them for 1s. You take 10% more damage for 4s.' },
  TACKLE: { name: 'Tackle', desc: 'Flying Kick deals much more knockback and increases Collide damage by an additional +150% +60% +10%.' },
  TAUNT: { name: 'Taunt', desc: "Provoke's cooldown is lowered by -3s." },
  TEMBLOR: { name: 'Temblor', desc: 'Bash gains +1 Area of Effect and is 0.05s faster.' },
  TIDAL_DRIFT: { name: 'Tidal Drift', desc: 'Flying Kick will instead send you forwards. This effect is limited to once per Charge cast.' },
  TOTEMIC_FUSE: { name: 'Totemic Fuse', desc: "Totemic Smash deals +40% +90% +90% +60% at the cost of half of Totem's duration." },
  TRANSCENDENCE: { name: 'Transcendence', desc: '25% chance for spells to cost no mana when casted.' },
  WINDSURF: { name: 'Windsurf', desc: "Arrow Shield now boosts your movement speed instead of blocking damage. Escape and Leap's vertical velocity are increased." },
  SAVIOURS_SACRIFICE: { name: "Saviour's Sacrifice", desc: 'While under 50% maximum health, nearby allies gain 15% bonus damage and defense.' },
};

export function getMajorIdDisplayName(apiId: string): string {
  return MAJOR_ID_INFO[apiId]?.name ?? apiId.replace(/^DESC_/, '').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).replace(/\bOf\b/g, 'of').replace(/\bThe\b/g, 'the');
}

export function getMajorIdDescription(apiId: string): string | null {
  return MAJOR_ID_INFO[apiId]?.desc ?? null;
}
