/** Full display names for item IDs (Build Solver, Recipe Solver, Search). */
export const NUMERIC_ID_FULL_NAMES: Record<string, string> = {
  relevance: 'Relevance',
  level: 'Combat Level',
  baseDps: 'Base DPS',
  slots: 'Powder Slots',
  hp: 'Health',
  hpBonus: 'Health Bonus',
  hprRaw: 'Raw Health Regen',
  hprPct: 'Health Regen %',
  mr: 'Mana Regen',
  ms: 'Mana Steal',
  ls: 'Life Steal',
  sdPct: 'Spell Damage %',
  sdRaw: 'Spell Damage Raw',
  mdPct: 'Melee Damage %',
  mdRaw: 'Melee Damage Raw',
  poison: 'Poison',
  spd: 'Walk Speed Bonus',
  atkTier: 'Attack Speed Bonus',
  averageDps: 'Average DPS',
  str: 'Strength',
  dex: 'Dexterity',
  int: 'Intelligence',
  def: 'Defense',
  agi: 'Agility',
  strReq: 'Strength Min',
  dexReq: 'Dexterity Min',
  intReq: 'Intelligence Min',
  defReq: 'Defense Min',
  agiReq: 'Agility Min',
  eDef: 'Earth Defense',
  tDef: 'Thunder Defense',
  wDef: 'Water Defense',
  fDef: 'Fire Defense',
  aDef: 'Air Defense',
  eDamPct: 'Earth Damage %',
  tDamPct: 'Thunder Damage %',
  wDamPct: 'Water Damage %',
  fDamPct: 'Fire Damage %',
  aDamPct: 'Air Damage %',
  damPct: 'Damage %',
  rDamPct: 'Elemental Damage %',
  nDamPct: 'Neutral Damage %',
  lvl: 'Combat Level',
  reqTotal: 'Req Total',
  skillPointTotal: 'Skill Point Total',
  offenseScore: 'Offense Score',
  ehpProxy: 'EHP Proxy',
  utilityScore: 'Utility Score',
  spPct1: '1st Spell Cost %',
  spRaw1: '1st Spell Cost Raw',
  spPct2: '2nd Spell Cost %',
  spRaw2: '2nd Spell Cost Raw',
  spPct3: '3rd Spell Cost %',
  spRaw3: '3rd Spell Cost Raw',
  spPct4: '4th Spell Cost %',
  spRaw4: '4th Spell Cost Raw',
  sumSpPct: 'Sum Spell Cost %',
  sumSpRaw: 'Sum Spell Cost Raw',
};

export function formatNumericIdLabel(key: string): string {
  return NUMERIC_ID_FULL_NAMES[key] ?? key;
}
